# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import djchoices.choices


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='nombre')),
                ('email', models.EmailField(db_index=True, max_length=254, null=True, unique=True)),
                ('tel', models.CharField(max_length=15, null=True)),
                ('ciudad', models.CharField(default='San Pedro Sula', max_length=50)),
                ('pais', models.CharField(default='Honduras', max_length=50)),
                ('rtn', models.CharField(max_length=16)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='nombre')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('identidad', models.TextField(max_length=13)),
                ('telefono', models.TextField(max_length=13)),
                ('empleado', models.BooleanField()),
                ('incentivo_por_dia', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='nombre')),
                ('fecha_vence', models.DateField(default=django.utils.timezone.now)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('markup', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CotizacionDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('_monto', models.DecimalField(db_column='monto', decimal_places=2, max_digits=10)),
                ('markup', models.DecimalField(decimal_places=2, max_digits=5)),
                ('_total', models.DecimalField(db_column='total', decimal_places=2, max_digits=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.Cotizacion', verbose_name='cotizacion')),
            ],
            options={
                'verbose_name': 'Detalle de Cotización',
                'verbose_name_plural': 'Detalles de Cotización',
                'ordering': ('-creado',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='nombre')),
                ('tipo_item', models.CharField(choices=[('Insumo', 'Insumo'), ('Servicio', 'Servicio'), ('Subcontratado', 'Subcontratado'), ('Cargo', 'Cargo'), ('Descuento', 'Descuento'), ('Impuesto', 'Impuesto'), ('Grupo', 'Grupo')], default='Servicio', max_length=13, validators=[djchoices.choices.ChoicesValidator({'Cargo': 'Cargo', 'Descuento': 'Descuento', 'Grupo': 'Grupo', 'Impuesto': 'Impuesto', 'Insumo': 'Insumo', 'Servicio': 'Servicio', 'Subcontratado': 'Subcontratado'})])),
                ('unidad', models.CharField(max_length=50)),
                ('costo', models.DecimalField(decimal_places=4, max_digits=10)),
                ('precio', models.DecimalField(decimal_places=4, max_digits=10)),
                ('descripcion_compra', models.CharField(max_length=50)),
                ('descripcion_venta', models.CharField(max_length=50)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='nombre')),
                ('fecha_desde', models.DateField(verbose_name='inicia')),
                ('fecha_hasta', models.DateField(verbose_name='termina')),
                ('estatus', models.CharField(choices=[('Solicitado', 'Solicitado'), ('Cotizado', 'Cotizado'), ('Confirmado', 'Confirmado'), ('Facturado', 'Facturado'), ('Cerrado', 'Cerrado')], default='Solicitado', max_length=10, validators=[djchoices.choices.ChoicesValidator({'Cerrado': 'Cerrado', 'Confirmado': 'Confirmado', 'Cotizado': 'Cotizado', 'Facturado': 'Facturado', 'Solicitado': 'Solicitado'})])),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.Cliente', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'Itinerario',
                'verbose_name_plural': 'Itinerarios',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='codigo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='NivelDePrecio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='nombre')),
                ('tipo', models.CharField(choices=[('Porcentaje', 'Porcentaje'), ('Valor', 'Valor')], default='Porcentaje', max_length=10, validators=[djchoices.choices.ChoicesValidator({'Porcentaje': 'Porcentaje', 'Valor': 'Valor'})])),
                ('accion', models.CharField(choices=[('Incrementa', 'Incrementa'), ('Decrementa', 'Decrementa')], default='Incrementa', max_length=10, validators=[djchoices.choices.ChoicesValidator({'Decrementa': 'Decrementa', 'Incrementa': 'Incrementa'})])),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('_factor', models.DecimalField(db_column='factor', decimal_places=4, max_digits=5, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nivel de Precio',
                'verbose_name_plural': 'Niveles de Precio',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annio', models.IntegerField(choices=[(2016, 2016), (2017, 2017), (2018, 2018)], default=2017, verbose_name='Año')),
                ('nombre', models.CharField(max_length=25)),
                ('valor', models.CharField(max_length=100)),
                ('unidad', models.CharField(max_length=100)),
                ('orden', models.IntegerField(default=0)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, overwrite=True, populate_from=('annio', 'nombre'))),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parámetro',
                'verbose_name_plural': 'Parámetros',
                'ordering': ['annio', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='TipoDeVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='nombre')),
                ('rendimiento', models.IntegerField()),
                ('costo_por_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_por_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacidad_nominal', models.IntegerField()),
                ('capacidad_real', models.IntegerField()),
                ('galones_tanque', models.DecimalField(decimal_places=2, max_digits=6)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Vehículo',
                'verbose_name_plural': 'Tipos de Vehículo',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Tramo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='codigo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('codigo', models.TextField(max_length=7)),
                ('desde_hacia', models.TextField(max_length=100)),
                ('kms', models.IntegerField()),
                ('hrs', models.DecimalField(decimal_places=1, max_digits=4)),
                ('codigo_desde', models.CharField(max_length=7)),
                ('codigo_hacia', models.CharField(max_length=7)),
                ('desde_lugar', models.ManyToManyField(related_name='desde', to='transporte.Lugar', verbose_name='desde')),
                ('hacia_lugar', models.ManyToManyField(related_name='hacia', to='transporte.Lugar', verbose_name='hacia')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=5)),
                ('placa', models.CharField(max_length=10)),
                ('chofer_fijo', models.BooleanField()),
                ('fecha_adquirido', models.DateField(blank=True, null=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='nombre')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='transporte.TipoDeVehiculo', verbose_name='tipo')),
            ],
            options={
                'ordering': ('-creado',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='parametro',
            unique_together=set([('annio', 'nombre')]),
        ),
        migrations.AddField(
            model_name='cotizaciondetalle',
            name='item',
            field=models.ManyToManyField(to='transporte.Item', verbose_name='item'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='itinerario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.Itinerario', verbose_name='itinerario'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nivel_de_precio',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='transporte.NivelDePrecio', verbose_name='nivel de precio'),
        ),
    ]
