# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-13 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conductor',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Conductores'},
        ),
        migrations.AlterModelOptions(
            name='lugar',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Lugares'},
        ),
    ]
