# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-13 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0002_auto_20170213_0838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='niveldeprecio',
            options={'ordering': ('valor',), 'verbose_name': 'Nivel de Precio', 'verbose_name_plural': 'Niveles de Precio'},
        ),
        migrations.AlterField(
            model_name='niveldeprecio',
            name='_factor',
            field=models.DecimalField(blank=True, db_column='factor', decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='niveldeprecio',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
