# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-14 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0003_auto_20170213_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramo',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='tramo',
            name='codigo_desde',
        ),
        migrations.RemoveField(
            model_name='tramo',
            name='codigo_hacia',
        ),
        migrations.AddField(
            model_name='tramo',
            name='_codigo',
            field=models.TextField(db_column='codigo', default='', max_length=7),
            preserve_default=False,
        ),
    ]
