# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-14 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0004_auto_20170214_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramo',
            name='_codigo',
            field=models.TextField(blank=True, db_column='codigo', max_length=7),
        ),
    ]
