# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-14 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0005_auto_20170214_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramo',
            name='desde_lugar',
        ),
        migrations.AddField(
            model_name='tramo',
            name='desde_lugar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='desde', to='transporte.Lugar', verbose_name='desde'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='tramo',
            name='hacia_lugar',
        ),
        migrations.AddField(
            model_name='tramo',
            name='hacia_lugar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hacia', to='transporte.Lugar', verbose_name='hacia'),
            preserve_default=False,
        ),
    ]
