# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-14 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0006_auto_20170214_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramo',
            name='hrs',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='tramo',
            name='kms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
