# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-15 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0008_auto_20170214_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramo',
            name='nombre',
        ),
    ]
