# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-15 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0010_auto_20170214_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramo',
            name='desde_lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desde', to='transporte.Lugar', verbose_name='origen'),
        ),
        migrations.AlterField(
            model_name='tramo',
            name='hacia_lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hacia', to='transporte.Lugar', verbose_name='destino'),
        ),
    ]
