# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-15 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import djchoices.choices


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0011_auto_20170214_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizaciondetalle',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='cotizaciondetalle',
            name='markup',
        ),
        migrations.RemoveField(
            model_name='cotizaciondetalle',
            name='precio',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='nivel_de_precio',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='transporte.NivelDePrecio', verbose_name='nivel de precio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizaciondetalle',
            name='_costo',
            field=models.DecimalField(db_column='costo', decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizaciondetalle',
            name='_descripcion',
            field=models.CharField(db_column='descripcion', default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizaciondetalle',
            name='_markup',
            field=models.DecimalField(db_column='markup', decimal_places=4, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizaciondetalle',
            name='nivel_de_precio',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='transporte.NivelDePrecio', verbose_name='nivel de precio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerario',
            name='nivel_de_precio',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='transporte.NivelDePrecio', verbose_name='nivel de precio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lugar',
            name='zona',
            field=models.CharField(choices=[('1', b'Uno'), ('2', b'Dos'), ('3', b'Tres')], default='1', max_length=4, validators=[djchoices.choices.ChoicesValidator({'1': b'Uno', '2': b'Dos', '3': b'Tres'})]),
        ),
        migrations.AddField(
            model_name='tramo',
            name='_cruza_frontera',
            field=models.BooleanField(db_column='cruza_frontera', default=False),
        ),
        migrations.AddField(
            model_name='tramo',
            name='_zona_destino',
            field=models.CharField(blank=True, db_column='zona_destino', max_length=4, null=True),
        ),
        migrations.RemoveField(
            model_name='cotizaciondetalle',
            name='item',
        ),
        migrations.AddField(
            model_name='cotizaciondetalle',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transporte.Item', verbose_name='item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cotizaciondetalle',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='item'),
        ),
    ]
