# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-15 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0012_auto_20170215_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='nivel_de_precio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transporte.NivelDePrecio', verbose_name='nivel de precio'),
        ),
        migrations.AlterField(
            model_name='cotizaciondetalle',
            name='nivel_de_precio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transporte.NivelDePrecio', verbose_name='nivel de precio'),
        ),
        migrations.AlterField(
            model_name='itinerario',
            name='nivel_de_precio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transporte.NivelDePrecio', verbose_name='nivel de precio'),
        ),
    ]
