# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-15 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0013_auto_20170215_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizaciondetalle',
            name='_costo',
            field=models.DecimalField(blank=True, db_column='costo', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cotizaciondetalle',
            name='_descripcion',
            field=models.CharField(blank=True, db_column='descripcion', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cotizaciondetalle',
            name='_markup',
            field=models.DecimalField(blank=True, db_column='markup', decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='cotizaciondetalle',
            name='_monto',
            field=models.DecimalField(blank=True, db_column='monto', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cotizaciondetalle',
            name='_total',
            field=models.DecimalField(blank=True, db_column='total', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cotizaciondetalle',
            name='nivel_de_precio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transporte.NivelDePrecio', verbose_name='nivel de precio'),
        ),
    ]
