# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-15 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0014_auto_20170215_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='_subtotal',
            field=models.DecimalField(blank=True, db_column='subtotal', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cotizaciondetalle',
            name='cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='transporte.Cotizacion', verbose_name='cotizacion'),
        ),
    ]
