# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-16 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0015_auto_20170215_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizaciondetalle',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='transporte.Item', verbose_name='item'),
        ),
    ]
