# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-17 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0016_auto_20170215_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='_subtotal',
            field=models.DecimalField(blank=True, db_column='subtotal', decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cotizaciondetalle',
            name='_costo',
            field=models.DecimalField(blank=True, db_column='costo', decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cotizaciondetalle',
            name='_markup',
            field=models.DecimalField(blank=True, db_column='markup', decimal_places=4, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='cotizaciondetalle',
            name='_monto',
            field=models.DecimalField(blank=True, db_column='monto', decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cotizaciondetalle',
            name='_total',
            field=models.DecimalField(blank=True, db_column='total', decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
