# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-17 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0017_auto_20170216_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizaciondetalle',
            name='_costo',
        ),
        migrations.RemoveField(
            model_name='cotizaciondetalle',
            name='_markup',
        ),
        migrations.RemoveField(
            model_name='cotizaciondetalle',
            name='_monto',
        ),
        migrations.RemoveField(
            model_name='cotizaciondetalle',
            name='_total',
        ),
        migrations.AddField(
            model_name='cotizaciondetalle',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='cotizaciondetalle',
            name='markup',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=6),
        ),
        migrations.AddField(
            model_name='cotizaciondetalle',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='cotizaciondetalle',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
