# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-17 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0018_auto_20170216_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='markup',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='total',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='_markup',
            field=models.DecimalField(blank=True, db_column='markup', decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='_total',
            field=models.DecimalField(blank=True, db_column='total', decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
