# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-17 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0019_auto_20170216_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='_markup',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='_utilidad',
            field=models.DecimalField(blank=True, db_column='utilidad', decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
