# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0020_auto_20170216_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizaciondetalle',
            options={'ordering': ('id',), 'verbose_name': 'Detalle de Cotizaci\xf3n', 'verbose_name_plural': 'Detalles de Cotizaci\xf3n'},
        ),
    ]
