# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-31 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import djchoices.choices


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0021_auto_20170301_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='zona',
            field=models.CharField(choices=[('1', 'Uno'), ('2', 'Dos'), ('3', 'Tres')], default='1', max_length=4, validators=[djchoices.choices.ChoicesValidator({'1': 'Uno', '2': 'Dos', '3': 'Tres'})]),
        ),
    ]
