# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0045_auto_20170513_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tramoenvehiculo',
            options={'ordering': ('tramo',), 'verbose_name': 'Tramo en Veh\xedculos', 'verbose_name_plural': 'Tramos En Veh\xedculos'},
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='_utilidad',
            field=models.DecimalField(blank=True, db_column='utilidad', decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='descripcion',
            field=models.CharField(default=' - ', max_length=100),
        ),
        migrations.AlterField(
            model_name='cotizaciondetalle',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cotizaciondetalle',
            name='utilidad',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6),
        ),
    ]
